### ISSUE TITLE
Nmcli0990Wireless - connect() - set interface

### ISSUE THREAD

**Issue by mwarzynski** [joshvillbrandt/wireless#13]
**Problem**
I have more than one interface. I wanted to connect with the network using interface with the strongest signal. Actually, I specified interface manually just before connect() and it didn't work.
By saying, didn't work I mean network-manager tried to estabilish connection, but with other interface than I specified.

**My solution**:
I needed to change nmcli command in this place - https://github.com/joshvillbrandt/wireless/blob/master/wireless/Wireless.py#L263 for:

```
# attempt to connect
response = cmd('nmcli dev wifi con {} password {} ifname {}'.format(
    ssid, password, self._interface))
```

If it matters, I am using Kubuntu 16.04 LTS.

**Comment by joshvillbrandt** [comment]
@mwarzynski, is the only difference here removing the letters "nect" from "connect"? Just out of curiosity, do you know why that fixes that (and how it mostly worked before then?)

A pull request would be appreciated! Thanks.

**Comment by mwarzynski** [comment]
@joshvillbrandt Yes, it seems the only difference is removed `nect`. Unfortunately, I don't remember what was my `nmcli` version back then.

As for now:
```
~ nmcli --version    
nmcli tool, version 1.14.7dev+3+g353743b99-1
```
```
~ nmcli dev wifi help
...
ARGUMENTS := connect
```
There is a full `connect` argument, so accordingly to my current nmcli version there is no bug.

Actually, I suppose `con` is just a shortcut for `connect`.

**Comment by mwarzynski** [comment]
I am not able to reproduce this bug anymore.
