### ISSUE TITLE
WPS connect

### ISSUE THREAD

**Issue by Chaostheorie** [joshvillbrandt/wireless#35]
This is more an question as an issue. So I am currently working at a workspace, where my machine (raspberry pi 3b) needs to connect to a wps network via a python script. Long story short question: is wps supported by this package and if how is it to use properly at a "normal" wps network. 
Thanks for any answers.

**Comment by joshvillbrandt** [comment]
Hi, @Chaostheorie. I haven't worked with WPS before. If the underlying network manager that you'd be using (see README.md) supports WPS, then it might work.

Please note that in general this repo is no longer maintained.

**Comment by Chaostheorie** [comment]
Little but late but thanks for the answer
